### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by blink1073**
- Allow internet for resource files
- Update to latest commit

### CODE REVIEW

**Comment by blink1073** [comment]
I do not have merge access on this repo, @matthew-brett.  Feel free to add me if you like :smile:

**Comment by matthew-brett** [comment]
I think you do have access - are you sure you don't?

**Comment by matthew-brett** [comment]
Oops - I forgot to add the repository to the team with permissions - done now - you should have admin access.

**Comment by blink1073** [comment]
Confirmed, cheers.

**Pull request merged**
